import { randomBytes } from 'node:crypto';
import { query } from '../client.js';
import { encrypt, decrypt } from '../../crypto.js';

/**
 * H-3 repository for handoff_webhooks — the per-workflow platform→workflow send
 * target. The secret is generated by the platform, ENCRYPTED at rest (never hashed —
 * we must decrypt to HMAC-sign outbound bodies), and only ever leaves the server via
 * an explicit owner/admin "reveal". Every function is tenant-scoped.
 */

export type WebhookDeliveryStatus = 'sent' | 'rejected' | 'failed';

export interface HandoffWebhookRow {
  id: string;
  tenant_id: string;
  n8n_workflow_id: string;
  url: string;
  secret_encrypted: string;
  enabled: boolean;
  last_delivery_at: Date | null;
  last_delivery_status: WebhookDeliveryStatus | null;
  created_at: Date;
  updated_at: Date;
}

/** Decrypted view for the send pipeline (url + signing secret + kill switch). */
export interface WebhookForSend {
  url: string;
  secret: string;
  enabled: boolean;
}

/** A fresh platform webhook secret: "whs_" + 32 crypto-random bytes (base64url). */
export function generateWebhookSecret(): string {
  return `whs_${randomBytes(32).toString('base64url')}`;
}

/**
 * Create-or-update the webhook URL for a workflow. On FIRST creation a secret is
 * generated and returned once (createdSecret); updating an existing row only changes
 * the URL and preserves the secret + enabled flag. Race-safe via ON CONFLICT.
 */
export async function upsertWebhook(params: {
  tenantId: string;
  n8nWorkflowId: string;
  url: string;
}): Promise<{ row: HandoffWebhookRow; createdSecret: string | null }> {
  const { tenantId, n8nWorkflowId, url } = params;

  // Existing row → just update the URL (keep secret + enabled).
  const updated = await query<HandoffWebhookRow>(
    `UPDATE handoff_webhooks SET url = $3, updated_at = now()
      WHERE tenant_id = $1 AND n8n_workflow_id = $2
      RETURNING *`,
    [tenantId, n8nWorkflowId, url],
  );
  if (updated.rows[0]) return { row: updated.rows[0], createdSecret: null };

  // New row → mint + encrypt a secret. ON CONFLICT DO NOTHING handles a create race.
  const secret = generateWebhookSecret();
  const inserted = await query<HandoffWebhookRow>(
    `INSERT INTO handoff_webhooks (tenant_id, n8n_workflow_id, url, secret_encrypted)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (tenant_id, n8n_workflow_id) DO NOTHING
     RETURNING *`,
    [tenantId, n8nWorkflowId, url, encrypt(secret)],
  );
  if (inserted.rows[0]) return { row: inserted.rows[0], createdSecret: secret };

  // Lost the create race → the row now exists; update its URL.
  const raced = await query<HandoffWebhookRow>(
    `UPDATE handoff_webhooks SET url = $3, updated_at = now()
      WHERE tenant_id = $1 AND n8n_workflow_id = $2
      RETURNING *`,
    [tenantId, n8nWorkflowId, url],
  );
  return { row: raced.rows[0], createdSecret: null };
}

/** The raw row (with encrypted secret) — for the registration UI's status display. */
export async function getWebhookRow(
  tenantId: string,
  n8nWorkflowId: string,
): Promise<HandoffWebhookRow | null> {
  const r = await query<HandoffWebhookRow>(
    `SELECT * FROM handoff_webhooks WHERE tenant_id = $1 AND n8n_workflow_id = $2`,
    [tenantId, n8nWorkflowId],
  );
  return r.rows[0] ?? null;
}

/** Decrypted url + secret + enabled for the send pipeline; null if none registered. */
export async function getWebhookForWorkflow(
  tenantId: string,
  n8nWorkflowId: string,
): Promise<WebhookForSend | null> {
  const row = await getWebhookRow(tenantId, n8nWorkflowId);
  if (!row) return null;
  return { url: row.url, secret: decrypt(row.secret_encrypted), enabled: row.enabled };
}

/** Decrypt + return the secret for an explicit owner/admin reveal; null if none. */
export async function revealWebhookSecret(
  tenantId: string,
  n8nWorkflowId: string,
): Promise<string | null> {
  const row = await getWebhookRow(tenantId, n8nWorkflowId);
  return row ? decrypt(row.secret_encrypted) : null;
}

/** Replace the secret (regenerate). Returns the new raw secret, or null if no row. */
export async function rotateWebhookSecret(
  tenantId: string,
  n8nWorkflowId: string,
): Promise<string | null> {
  const secret = generateWebhookSecret();
  const r = await query(
    `UPDATE handoff_webhooks SET secret_encrypted = $3, updated_at = now()
      WHERE tenant_id = $1 AND n8n_workflow_id = $2`,
    [tenantId, n8nWorkflowId, encrypt(secret)],
  );
  return (r.rowCount ?? 0) > 0 ? secret : null;
}

/** Flip the enabled kill switch. Returns true iff a row was updated. */
export async function setWebhookEnabled(
  tenantId: string,
  n8nWorkflowId: string,
  enabled: boolean,
): Promise<boolean> {
  const r = await query(
    `UPDATE handoff_webhooks SET enabled = $3, updated_at = now()
      WHERE tenant_id = $1 AND n8n_workflow_id = $2`,
    [tenantId, n8nWorkflowId, enabled],
  );
  return (r.rowCount ?? 0) > 0;
}

/** Record the outcome of the most recent delivery attempt (cheap health signal). */
export async function setDeliveryResult(
  tenantId: string,
  n8nWorkflowId: string,
  status: WebhookDeliveryStatus,
): Promise<void> {
  await query(
    `UPDATE handoff_webhooks
        SET last_delivery_at = now(), last_delivery_status = $3, updated_at = now()
      WHERE tenant_id = $1 AND n8n_workflow_id = $2`,
    [tenantId, n8nWorkflowId, status],
  );
}

/** Remove a workflow's webhook. Returns true iff a row was deleted. */
export async function deleteWebhook(tenantId: string, n8nWorkflowId: string): Promise<boolean> {
  const r = await query(
    `DELETE FROM handoff_webhooks WHERE tenant_id = $1 AND n8n_workflow_id = $2`,
    [tenantId, n8nWorkflowId],
  );
  return (r.rowCount ?? 0) > 0;
}
